# Generated by Django 5.0.1 on 2024-01-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video/')),
                ('json_file', models.FileField(blank=True, null=True, upload_to='json/')),
            ],
        ),
    ]
